quarkus.datasource.db-kind=postgresql 
quarkus.datasource.username=${DB_USER}
quarkus.datasource.password=${DB_PASSWORD}

# quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/statushub
quarkus.hibernate-orm.database.generation=update

quarkus.hibernate-orm.schema-management.strategy=update

mp.jwt.verify.publickey.location=classpath:.certs/public.pem
smallrye.jwt.sign.key.location=classpath:.certs/private.key
mp.jwt.verify.issuer=${JWT_ISSUER}
quarkus.native.resources.includes=./.certs/public.pem